### ISSUE TITLE
Instructions to compile/build?

### ISSUE THREAD

**Issue by T10a** [MrCrayfish/ModelCreator#117]
Hello,
I'm just wondering how I could compile this code to use the newest version of the Model Creator. There doesn't seem to be any instructions listed in a wiki or an attached document.

**Comment by MrCrayfish** [comment]
Right now it's a little fidgety. I have to create a fat jar using JarSplice to put all the libraries and natives together. For a rough instructions, export in eclipse as a Jar, not Runnable Jar. Download JarSplice, add the exported Jar and all libraries within libs. For natives, add all the files from the windows, mac, and linux folders within the natives folder. Then set the main class to "com.mrcrafish.modelcreator.Start". Finally export.

**Comment by T10a** [comment]
I used that method, and I got this as an error when I ran it in a terminal:
`Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	String cannot be resolved to a type
	Double cannot be resolved to a type
	Double cannot be resolved
	System cannot be resolved
	JOptionPane cannot be resolved
	System cannot be resolved
	Properties cannot be resolved to a type
	Properties cannot be resolved to a type
	FastLookAndFeel cannot be resolved
	UIManager cannot be resolved
	Exception cannot be resolved to a type
	String cannot be resolved to a type
	String cannot be resolved to a type

	at src.com.mrcrayfish.modelcreator.Start.main(Start.java:12)`

**Comment by MrCrayfish** [comment]
Very strange. That error occurs when classes are not known at compile time, and worse it's the Java libraries!
