### ISSUE TITLE
Issues with transparency/translucency

### ISSUE THREAD

**Issue by Blistening** [MrCrayfish/ModelCreator#128]
When I try adding a translucent [Semi-Transparent] or a transparent texture model such as black stained glass to a 3d model it just turns to the same color but without transparency. Can someone help?
Furnace:
https://gyazo.com/3675ab749a037f585a4c784c2f314680

The black part in the middle is suppose to be black stained glass, but it turns into a solid gray color.

**Comment by KnightMiner** [comment]
There is an option in the menu to show proper transparency IIRC, but note that in game it will not appear transparent unless the block supports it.

**Comment by MrCrayfish** [comment]
Please refer to KnightMiner's comment.
