### ISSUE TITLE
some minecraft render problems

### ISSUE THREAD

**Issue by TheMorc** [MrCrayfish/ModelCreator#134]
i am making mod but i saw that when i make any model in game looks good but some parts of it dissappears and when i move behind and back, rotate player,  some other parts dissappear, i have newest version of nvidia drivers but still..,  https://postimg.org/image/mn9xif3bh/ https://postimg.org/image/s0ekh6wbx/
https://postimg.org/image/c3fskh3xp/

**Comment by TheMorc** [comment]
i fixed it. it was transculent modifier in block, but then after nvidia driver update, modelcreator main renderer stopped working showing only gray screen like someone before me, but i switched main monitor to Intel GPU and works now

**Comment by AndersBillLinden** [comment]
Nice to hear! Can you close the issue, please?
