### ISSUE TITLE
UV is not a 4-tuple.

### ISSUE THREAD

**Issue by drXor** [MrCrayfish/ModelCreator#14]
UV editing is currently too limited, especially since some of my models use spritesheet-like textures, which are sliced by careful selection of UV coordinates. It would be useful to have some way of specifying raw coordinates.

**Comment by MrCrayfish** [comment]
Im assuming a min and max UV. I'll see what I can do

**Comment by MrCrayfish** [comment]
Done. You can now specify the start and end uv in the faces panel.
