### ISSUE TITLE
[Feature Request] Ability to rotate face on multiple axis

### ISSUE THREAD

**Issue by Dockter** [MrCrayfish/ModelCreator#148]
Hello.  My wife is currently using this to do some models for our Minecraft server.  We are looking to have the ability to rotate a face on two axis's, currently this tool only seems to support one at a time.

Thank you for your time.

**Comment by MrCrayfish** [comment]
Rotation on an axis is restricted to one due to how Minecraft.

**Comment by Dockter** [comment]
Can you elaborate?  We can do this with an OBJ just fine.  Is it the json reader that is causing this restriction?

**Comment by MrCrayfish** [comment]
JSON models have limits unfortunately.

**Comment by Dockter** [comment]
If you can elaborate I'll work with our development team to get a fix for it into Forge.
