### ISSUE TITLE
Download on website not working

### ISSUE THREAD

**Issue by Romnia** [MrCrayfish/ModelCreator#152]

**Comment by raphaeliG** [comment]
Neither do I. The moment the timer on the website hits "Enjoy" the webpage refreshes itself cancelling the download and resetting the timer, in an infinite loop.

**Comment by ArjunMadana** [comment]
I have also experienced this problem

**Comment by Cyclip** [comment]
I can't download it
It says 'Enjoy!' and reloads the page and loops.

**Comment by tigerza117** [comment]
now not working
so sad
i need like download

**Comment by TheHDCrafter** [comment]
Same :-(

**Comment by EnderStrider** [comment]
same here .

**Comment by Burgersim** [comment]
same here, is it possible to just build it from the source code maybe?

**Comment by mercadanteus** [comment]
You can download an executable version of Model Creator here:
https://github.com/mercadanteus/minecraft-new-forniture-/tree/Model-Creator-executable

**Comment by AlexejheroYTB** [comment]
Same issue
@MrCrayfish

**Comment by Davoleo** [comment]
Same for me

**Comment by Michaelstone007** [comment]
Guys! I've been downloaded the lastest (pre-4) version, you can download it here.:
[http://zipansion.com/2uitj](url)

**Comment by mercadanteus** [comment]
Already bought Cubik Studio :)

**Comment by Aethengames** [comment]
Its missing the link now thats why its not working (i inspected it)

**Comment by ehamawy** [comment]
Confirmed still down

**Comment by Zanna22** [comment]
Me too. When I click download windows pre4 it say: your download is starting but when there is enjoy the page refresh itself. @MrCrayfish please resolve this bug as soon as possible.

**Comment by ryansleights** [comment]
me too

**Comment by MrCrayfish** [comment]
Fixed finally! 😂
