### ISSUE TITLE
No elements get exported.

### ISSUE THREAD

**Issue by SwatDoge** [MrCrayfish/ModelCreator#165]
Hello.

I mainly create models from my desktop, however, in version 0.7.0 and 0.6.0 (as far as I know) elements do not get exported what so ever. Normally I worked around this by saving the model as project and then exporting it using pre-0.4.0, but that version has auto UV when importing which is really annoying.

This is what my exported files look like: https://pastebin.com/raw/xNHYpzKd

On a rare occasion it does export, mainly when editing already existing models in a working resource pack. It is however not able to export models, textures and projects coming from your desktop. 

Hopefully this issue can be resolved, its constantly in the way of my projects. Thanks for the amazing program though :]

**Comment by MrCrayfish** [comment]
Faces that don't have textures won't be exported. Option will come soon in the export dialog.

**Comment by SwatDoge** [comment]
Thank you for the quick reply.

**Comment by SwatDoge** [comment]
> Faces that don't have textures won't be exported. Option will come soon in the export dialog.

Thank you for the quick reply
