### ISSUE TITLE
Crashs My Game

### ISSUE THREAD

**Issue by DanielNeff1234** [MrCrayfish/ModelCreator#177]
So I'm trying to make a trident look like a scythe in your model maker, and there are 76 cubes (don't know if that's important, just figured it might help to know that). When I put on the texture pack it crashed my game, but when I loaded it with optifine the model did load; just without a texture. This is the crash report

The game crashed whilst rendering overlay
Error: n: Non [a-z0-9/._-] character in path of location: minecraft:block/Pixel Color 3

I reopened your model maker with what should have been a fully completed model (I did save the model and it's textures), and for some reason All the textures that took me hours to place in are now gone! I don't know a thing about coding, so I'm clueless as to what happened. If you or anyone else could help me, that'd be greatly appreciated.

**Comment by jacksonhardaway** [comment]
If you read the error, it is saying you have an invalid texture name.

Textures should never have spaces or uppercases. Replace the spaces with underscores and the uppercased letters with lowercased letters.

**Comment by DanielNeff1234** [comment]
Oh!! Thank you so much dude! I know nothing about coding. I never would have figured that out.
