### ISSUE TITLE
[SUGGESTION] Rotate along X & Z

### ISSUE THREAD

**Issue by Shazuli** [MrCrayfish/ModelCreator#179]
Right now you can only rotate a model in the Y axis, but it would be nice to be able to rotate it in the other two axises.

**Comment by MrCrayfish** [comment]
That not how JSON models work. You're only allowed to rotate on one axis.

**Comment by Shazuli** [comment]
I have to disagree @MrCrayfish. Vanilla Minecraft rotates their models in the X axis too:

`blockstates/piston.json`
```json
{
    "variants": {
        "extended=false,facing=down": { "model": "block/piston", "x": 90 },
        "extended=false,facing=up": { "model": "block/piston", "x": 270 },
        "extended=false,facing=north": { "model": "block/piston" },
        "extended=false,facing=south": { "model": "block/piston", "y": 180 },
        "extended=false,facing=west": { "model": "block/piston", "y": 270 },
        "extended=false,facing=east": { "model": "block/piston", "y": 90 },
        "extended=true,facing=down": { "model": "block/piston_base", "x": 90 },
        "extended=true,facing=up": { "model": "block/piston_base", "x": 270 },
        "extended=true,facing=north": { "model": "block/piston_base" },
        "extended=true,facing=south": { "model": "block/piston_base", "y": 180 },
        "extended=true,facing=west": { "model": "block/piston_base", "y": 270 },
        "extended=true,facing=east": { "model": "block/piston_base", "y": 90 }
    }
}
```

And that is not what I ask in this issue. Your program's Y rotation function transforms the elements' coordinates in order to get a different JSON model. It's an editing program, not the game, so I feel like in an editing program you should be able to rotate the actual model in one or two axises.

**Comment by jacksonhardaway** [comment]
What you’re looking at are Blockstates. Blockstated are entirely different to the actual model and only changes how it looks when its at a certain state.

You can only rotate JSON model elements one axis at a time.
