### ISSUE TITLE
Won't open on Zorin 15.2

### ISSUE THREAD

**Issue by ALtaDoodler** [MrCrayfish/ModelCreator#185]
hi, just downloaded the modelling tool from your site, newest version 0.7.0. i have java 11 and 8 installed on my linux/zorin system. when double clicking, or specifying the java versions, the .jar file of the program doesn't open it, and using terminal brings up this:

![Screenshot from 2020-04-21 22-05-05](https://user-images.githubusercontent.com/64117835/79936677-abd4f600-841d-11ea-9ad8-0dcdacc034b7.png)

any ideas?

**Comment by MrCrayfish** [comment]
It looks more like an issue to do with the look and feel theme I use in the program. It's not something I can fix because it's not my code and Java programs often break on Linux when they do more than the basics.
