### ISSUE TITLE
only 1 axis rotation supported per cube

### ISSUE THREAD

**Issue by mateuszdrwal** [MrCrayfish/ModelCreator#19]
if you set the rotation of a cube, for example on the x axis and then change the axis to y, the x axis is reset and the y axis gets the current value of that drag thing. this makes it possible to make the cube stand on its edge
![zrzut ekranu 2015-04-05 13 27 07](https://cloud.githubusercontent.com/assets/11805733/6996707/7f5f7980-db97-11e4-94d2-851a80841c32.png)
 but in does not make it possible to make it stand on 1 corner.

**Comment by MrCrayfish** [comment]
Minecraft only allows rotation on one axis. This is something that can't be changed.

**Comment by mateuszdrwal** [comment]
thats unfortunate
