### ISSUE TITLE
I can't open the Model Creator 0.7.0, it just opens a CMD and closes

### ISSUE THREAD

**Issue by MrApollo163** [MrCrayfish/ModelCreator#190]
I tried many forms to solve it, but i can't, i don't know if its because i download it with Firefox or maybe the Java version, when i try to opne with Java it opnes a CMD tab and then the tab closes, everytime.

![Screenshot_12](https://user-images.githubusercontent.com/65457455/82123760-0fc2b400-9769-11ea-862f-e226abf7d029.jpg)

**Comment by MrApollo163** [comment]
Please, i need some help over here

**Comment by gabsilvcar** [comment]
Check your JRE installation by openning cmd and typing "java -version"
If it's properly installed, go to the folder where your jar is located in the file explorer and type cmd on the bar, after that just run it by using this command "java -jar model-creator.jar"(model-creator is the way I renamed it, but your's is probably 0.70.mc.jar or whatever).
Hope this helps!

**Comment by MrApollo163** [comment]
i'll try it, thx

**Comment by MrApollo163** [comment]
Okay, I'm back and it doesn't work, maybe it's an alternative problem, because I installed JRE 8 251, but it doesn't matter, I can use MCpre4, I know there are a lot of bugs, but it's the best I can do for myself

**Comment by MrApollo163** [comment]
Alright, i finally figured out what was happening, so i unistalled all java versions, i couldnt even open Minecraft, so i installed JRE 8 u51 and download the ModelCreator and it worked, i was totally hopeless these days, so thats give me some "energy", if you have passed through the same problem, just uninstall any other Java version (i used Revo Unistaller Free). So thx who helped me.
