### ISSUE TITLE
Model makes the ground invisible when looking at it

### ISSUE THREAD

**Issue by MasterBeiber** [MrCrayfish/ModelCreator#195]
![2020-06-22_16 03 48](https://user-images.githubusercontent.com/67171744/85330317-2b288980-b4a2-11ea-8df0-aae73a777be0.png)
I was making an iron table, but then when I place it down, the ground basically is x ray. I'm using a purpur block for the table.

**Comment by MasterBeiber** [comment]
leaves work

**Comment by natewilliford** [comment]
This happens for me too. What was the fix?

**Comment by natewilliford** [comment]
Setting .notSolid() in the block properties fixes it. So it makes sense that using the Leaves properties would work.
