### ISSUE TITLE
UV feature not changing 2nd set of cords

### ISSUE THREAD

**Issue by mateuszdrwal** [MrCrayfish/ModelCreator#20]
in the editor, the UV looks just fine, but when its generated in the JSON file the second set of cordinates is always 16, making my pumpkin look something like this:
![zrzut ekranu 2015-04-05 13 40 22](https://cloud.githubusercontent.com/assets/11805733/6996726/6aa64d6e-db99-11e4-9c42-dce90116db14.png)
also this is the json file generated:
![zrzut ekranu 2015-04-05 13 40 50](https://cloud.githubusercontent.com/assets/11805733/6996727/82488568-db99-11e4-9a16-7752d283966d.png)

**Comment by mateuszdrwal** [comment]
after that UV pull request its ok now

**Comment by MrCrayfish** [comment]
Yeah, I fixed it up in a new commit. The start UV is from the top left, the end UV is the bottom right
