### ISSUE TITLE
I need help with textures

### ISSUE THREAD

**Issue by infraeye** [MrCrayfish/ModelCreator#201]
Hello, MrCryfish. I 've been using your mods since they were like for 1.6 or something it was a long time ago i don't remember good ffs. Now I am using Model Creator and I would be really glad if someone tells me if I am able to put new kind of textures that are not in minecraft and make them seen in the resource pack. The Model is working great but the textures are missing and I am trying to find a way to put the custom non-minecraft textures work. Pleaaaase I need help

**Comment by mesquitaVictor** [comment]
do you tried to fix the resource pack?
watch this video 

https://www.youtube.com/watch?v=mzTlk8zc9rg

**Comment by MrCrayfish** [comment]
I don't really support the Model Creator anymore. I suggest using Blockbench.
