### ISSUE TITLE
when holding shift to slowly move the orgin, the decimals go CRAZY

### ISSUE THREAD

**Issue by mateuszdrwal** [MrCrayfish/ModelCreator#21]
this is probably easy to fix, i once had this problem in one of my JS apps, and it worked fine after i rounded the number. too bad i cant java and dont know how to use eclipse. also, quick question: do you update the executable at your site when you make any changes here? i just simply have problems compiling but thats beside the point

**Comment by MrCrayfish** [comment]
It has been fixed in the repository but not released yet.
