### ISSUE TITLE
cube behaving weird while orgin is moved

### ISSUE THREAD

**Issue by mateuszdrwal** [MrCrayfish/ModelCreator#22]
before you read this, i want you to know that there might be some logic to this thing that i dont understand.

if you move a cube to the orgin, and rotate it for example 90 degrees and then move the orgin up and down, i understand that the cube moves up and down, but the cube also moves away from the orgin, wich i dont understand.

![orgin bug](https://cloud.githubusercontent.com/assets/11805733/6997275/a06074f8-dbb6-11e4-8489-7d81f3593703.gif)

**Comment by MrCrayfish** [comment]
Yes, the logic is confusing and this is not intentional. It's simply how it behaves if you move the origin after the rotation. Really you should set the origin then the rotation, or it goes confusing as shown.
