### ISSUE TITLE
crashes while closing

### ISSUE THREAD

**Issue by mateuszdrwal** [MrCrayfish/ModelCreator#23]
for some reason the program crashes and stops responding after presssing the X, however the file>exit works just fine

**Comment by andre111** [comment]
Just fixed this. Will make a pull request once my current one is merged

**Comment by mateuszdrwal** [comment]
im pretty sure its fixed now

**Comment by mateuszdrwal** [comment]
actualy, it still crashes

**Comment by andre111** [comment]
Yeah, MrCrayfish tried fixing it himself, but he overlook the real problem.
I allready wrote a comment stating how to fix it properly but he didn't respond yet.

**Comment by mateuszdrwal** [comment]
fixed :D
