### ISSUE TITLE
I can open ModelCreator up, but not use it

### ISSUE THREAD

**Issue by AyanGithub** [MrCrayfish/ModelCreator#24]
http://pastebin.com/S1LQiC34 and it basically doesn't work I've imported the libs. I have latest commit as of April 6 (commit 3b2555c948)
![issuesmrcrayfishmodelcreator](https://cloud.githubusercontent.com/assets/11683855/7014549/5f765974-dc94-11e4-8148-ec5233916597.PNG)

**Comment by AyanGithub** [comment]
Again, 64-bit Windows 10 technical preview.

**Comment by MrCrayfish** [comment]
Add the res folder into the build path.
