### ISSUE TITLE
Add particle feature

### ISSUE THREAD

**Issue by mateuszdrwal** [MrCrayfish/ModelCreator#27]
its verry anoying to for every model have to go into the save and manualy enter the ("particle": "blocks/example") code. it would be nice if there was a feature to browse for the break particle before exporting.

**Comment by MrCrayfish** [comment]
Thank you for reminding me. That was a planned feature, and kinda forgot to work on it.

**Comment by mateuszdrwal** [comment]
is it just me or is this added? havent tested, but im pretty sure its done. ill reopen if not
