### ISSUE TITLE
When texture is rotated, the UV bar does not equal to the actual texture rendered

### ISSUE THREAD

**Issue by mateuszdrwal** [MrCrayfish/ModelCreator#31]
![zrzut ekranu 2015-04-12 12 01 14](https://cloud.githubusercontent.com/assets/11805733/7105171/b0c59d1e-e10b-11e4-9ab2-662285eb0f14.png)
i know kindof whats going on, but its realy confusing. it is realy hard to explain. but it would be kindof correct if the UV sidebar texture would not rotate, or if the UV box rodared with it, but that does not make any sense to me

**Comment by MrCrayfish** [comment]
Have you got the latest code? I fixed this problem

**Comment by mateuszdrwal** [comment]
yup i have commit 113

**Comment by mateuszdrwal** [comment]
i found it like 5 min before posting and i have compiled the files yesterday evning after you pushed out the latest commit

**Comment by mateuszdrwal** [comment]
maby you havent pushed that code out yet?

**Comment by mateuszdrwal** [comment]
"authorized a minute ago" dont forget to close ;)
