### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by mateuszdrwal** [MrCrayfish/ModelCreator#37]
and, the compiling method changed again. i guess im doing something wrong with the "res" folder becouse no canvas is loaded however the icons are

![zrzut ekranu 2015-04-30 16 05 25](https://cloud.githubusercontent.com/assets/11805733/7414404/c4648ba0-ef52-11e4-935a-cea9e72dbe0b.png)
![zrzut ekranu 2015-04-30 16 06 22](https://cloud.githubusercontent.com/assets/11805733/7414419/e088ab9a-ef52-11e4-8b45-150aed914734.png)

**Comment by MrCrayfish** [comment]
Check in the Start.java that "System.setProperty("org.lwjgl.librarypath", new File("natives/windows").getAbsolutePath());" isn't commented out

**Comment by mateuszdrwal** [comment]
it was. probably should change that in the commit huh? anyway, thank you!

**Comment by mateuszdrwal** [comment]
should i close this or wait until you remove the comment?
