### ISSUE TITLE
Model Creator don't open 

### ISSUE THREAD

**Issue by Matban** [MrCrayfish/ModelCreator#40]
When I open the model creator NORMAL, nothing happens. The exact if I want to open it with adminstrator.

**Comment by mateuszdrwal** [comment]
You gave us a lot of info there. are you using the Pre4 executeable or are you compiling the latest commit on your own? what OS is it? and there is nothing called modelcreator NORMAL.

**Comment by mateuszdrwal** [comment]
please reply or close this issue. it is sitting here for no reason because nobody else has this problem. my guess is that you are doing something wrong yourself.
