### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by mateuszdrwal** [MrCrayfish/ModelCreator#42]
i just cannot figure out how to remove the shadows from cubes when a block is next to it. for example, if there is a cube, and then in mc you place a block to the north of the block with the cube the north face of the cube becomes black. this probably does not happen with transparent blocks(havent tested), but im designing a bookshelf with a lot of cubes. also, if the feature alredy exists, i cannot find it. the shade checkbox does not seem to do anything for me.

**Comment by KnightMiner** [comment]
You might be experiencing [MC-51447](https://bugs.mojang.com/browse/MC-51447), so it is not a problem with the program.

**Comment by mateuszdrwal** [comment]
i am indeed. does this happen to everyone and is there a way to fix it outside of the program?

**Comment by KnightMiner** [comment]
None that I've found (other than night vision, but you cannot expect to have that all the time), we might just have to wait for Mojang to fix it

**Comment by mateuszdrwal** [comment]
ok, im closing the issue, and im also gonna remind mojang of that bug, as it is a realy easy fix and they have not fixed it for a year now.
