### ISSUE TITLE
cant find minecraft textuers

### ISSUE THREAD

**Issue by MinionGaming** [MrCrayfish/ModelCreator#46]
when i brows for textures i cant find them anywhere. PLZ tell me how.

**Comment by mateuszdrwal** [comment]
first of, please dont mark this an an issue. it is not a bug nor feature request

you can find all the textures in .minecraft\versions\1.8.X\1.8.X.jar\assets\minecraft\textures

you can open the jar file with winrar by right clicking and choosing open with>winrar

now close this issue

**Comment by mateuszdrwal** [comment]
please close this
