### ISSUE TITLE
your program is giving me a texture error "width and height must be a multiple of 16" even though the file was 32x32

### ISSUE THREAD

**Issue by RazzorWind** [MrCrayfish/ModelCreator#51]
So I recently got into modeling. While I was making a model and loading up textures for it, I got a random "texture error" stating that the file I had chosen was not a size multiple by 16. Even though the file was 32x32. I restarted the program, and even tried to add it manually in the .json. Nothing seed to work. Would there be a easy solution for this bug?

**Comment by mateuszdrwal** [comment]
isnt this the same as issue #49?

**Comment by RazzorWind** [comment]
Yes, I believe so. I'll go ahead and follow that issue.

**Comment by mateuszdrwal** [comment]
close this issue
