### ISSUE TITLE
[Request] Rotate on multiple axes

### ISSUE THREAD

**Issue by sebastienfulmer** [MrCrayfish/ModelCreator#58]
The rotation interface is well made, however I noticed when designing a campfire model, that when you switch axes, it resets the rotation. This is a problem for me with this particular model, as all the parts are at a 22,5 degree angle facing upwards, however 4 of the elements need to be tilted at 45 degrees so they will angle in towards the campfire. Maybe swap the dropdown for 3 separate sliders, one for each axis, so we can rotate on multiple axes simultaneously.

**Comment by KnightMiner** [comment]
Minecraft does not support rotation on more than one axis, thus the model creator does not either

**Comment by mateuszdrwal** [comment]
Yeah, i alredy requested this, but it is minecrafts fault because it only supports 1 axis rotations locked to 22,5 degrees. You can close this issue now.

**Comment by sebastienfulmer** [comment]
Is there a possible workaround though, I've seen models that look like they've been rotated on multiple axes, or is that only available with OBJ?

**Comment by KnightMiner** [comment]
Not that I've seen without the OBJ files (the occasional mod that updated to 1.8 still does it via OBJs). It does not even work using blockstate files, as while they also support rotation (including on two axis's), they only do it in 90 degree increments.

You can get finer rotation using item models, but it won't look that way if placed as a block, and it only supports rotating the whole model.

**Comment by MrCrayfish** [comment]
Unfortunately Minecraft does not support rotation on more than 1 axis. Sorrry about that :/
