### ISSUE TITLE
Y no build system?

### ISSUE THREAD

**Issue by drXor** [MrCrayfish/ModelCreator#6]
Hey, it'd be awesome if you can update this to use Maven/Gradle before you push the final version. I can't build it because I have IntelliJ, not Eclipse.

**Comment by MrCrayfish** [comment]
I tried converting to Maven but slick-util.jar is not in the maven repository. I know you can add jars locally but that would mean everyone would have to do the same thing. I recognize you from Reddit. I will send you a test jar soon.

**Comment by drXor** [comment]
Pretty sure you can just include anything there isn't a maven repo for in the git repo and point maven at it. Otherwise, you can always set up your own sonatype repo. They're useful to have.
