### ISSUE TITLE
Source code License?

### ISSUE THREAD

**Issue by tyronx** [MrCrayfish/ModelCreator#64]
Whats the License of the source code? GPL v2, MIT, Public domain? I'd be very thankful to know! :)

(a license.txt is missing in the root directory)

**Comment by MrCrayfish** [comment]
Added :)

**Comment by tyronx** [comment]
Hm that license.txt is unfortunately contradictory. See also
https://creativecommons.org/faq/#Does_my_use_violate_the_NonCommercial_clause_of_the_licenses.3F
and
http://www.gnu.org/philosophy/free-sw.html

CC-NC-SA is not an open source license, so to be correct you would need to remove the term "open source" from there, altough I would very much prefer it to be really open source :-)

Here is a list of approved open source licenses: https://opensource.org/licenses
