### ISSUE TITLE
Textures not being rendered - WIndows 7, JRE1.8.0_31

### ISSUE THREAD

**Issue by paultorben** [MrCrayfish/ModelCreator#7]
I have successfully built ModelCreator, and I can create, move, etc. cuboids, but I have yet to see a texture rendered.  I can disable faces from being displayed, but after selecting a texture from the file system, it does not display on the assigned face

I have tried debugging the code, but I have not had much luck there - the 'binded' value for my cuboid always comes up false, even though the texture file is present in the correct place. I'm wondering if perhaps I've just just missed a step when I am tying to assign a texture to a face - but the steps seem pretty self-explanatory.

I have also run some sample LWJGL programs, and I see their textures, so I think I can eliminate my graphics card driver from the equation (hopefully).

Anyway, excellent program, thanks for all your work, can't wait to start making models  : -)

ENV:  WIndows 7, JRE1.8.0_31

**Comment by MrCrayfish** [comment]
You need to make sure the texture is a multiple of 16, hence 16x, 32x, 64x, 128x

**Comment by paultorben** [comment]
I tested using 'repeater_off.png' and 'wool_colored_red.png' from 'build\tmp\recompSrc\assets\minecraft\models\block' (by following your excellent series on 1.8 Block Models) which i copied into the 'res' directory for ModelCreator

**Comment by paultorben** [comment]
Quick question - are you developing on Windows or Mac?

**Comment by MrCrayfish** [comment]
I am developing on Windows 7 with Java 8. I will push a new commit with some debugging JDialogs

**Comment by MrCrayfish** [comment]
Alright, I've pushed a new commit.

**Comment by paultorben** [comment]
Ok, downloaded and tested - I do not see the "default cube" or the dialog or its message "Texture successfully loaded" - as I had suspected the texture is not loading.

Just to make sure we're on the same page, I've attached an image of what the app looks like, after I have selected the texture from the file dialog.

Also the Eclipse Debug Output looks like (the first two lines are in red text): 
[LWJGL] Initial mode: 1920 x 1080 x 32 @60Hz
[LWJGL] MemoryUtil Accessor: AccessorUnsafe
TextureManager: loadTexture: name: brick
Thu Mar 26 18:18:48 PDT 2015 INFO:Use Java PNG Loader = true
brick

![modelcreator_texture_window](https://cloud.githubusercontent.com/assets/1790926/6860495/2758954a-d3e6-11e4-8f64-31c0361bd13b.png)

**Comment by MrCrayfish** [comment]
I don't think you have the latest commit. The program should look something like this.
![Screenshot](http://i.imgur.com/GjrSL2M.png)

**Comment by paultorben** [comment]
I had two issues - in the Texture manager, I never saw the "Brick" texture - also, my source was out-of-date as you said (not sure why, but possibly because of my debugs edits).  So posting that picture of how the Texture Manager should look was very helpful.

I started fresh, and fiddled around with the paths and now both of these issues have been resolved.  Thanks for your help !
