### ISSUE TITLE
Request - More refined controls - floats instead of integers 

### ISSUE THREAD

**Issue by lehjr** [MrCrayfish/ModelCreator#70]
To elaborate, it would be handy to not be limited to integer values in the controls. For instance, if I have a 1x1x1 cube and I want to center it, I have to do it manually by exporting the model to json, editing the file and importing it back again and the same with UV mapping. I realize this is a basic model editor, and it is great as it is, but it could be much more powerful with a couple tweaks.

**Comment by lehjr** [comment]
So after writing this I see this tooltip "Hold shift for decimals".  I don't think it works in Linux though. I ended up using an XP VirtualBox VM because this is kinda broken in Linux.

**Comment by SomeoneElse37** [comment]
You can also type into the controls (by clicking on the number shown) and enter as many decimal places as you like. The program will round the displayed number to the nearest tenth, but when you export, all the digits will still be there.
