### ISSUE TITLE
Ground beneath models is seethrough

### ISSUE THREAD

**Issue by mandm635** [MrCrayfish/ModelCreator#76]
If you create a model without fully covering the ground area, uncovered areas are seethrough/ xray glitch.

**Comment by KnightMiner** [comment]
That has nothing to do with the model maker. That is a Minecraft thong, and It is not a big there either. If a block is solid, it must cover all faces

**Comment by mandm635** [comment]
Any idea how to fix this? I added the block as part of my mod.

**Comment by MrCrayfish** [comment]
`@Override
	public boolean isOpaqueCube()
	{
		return false;
	}

	@Override
	public boolean isFullCube()
	{
		return false;
	}`
