### ISSUE TITLE
Rotation causes X-Ray effect

### ISSUE THREAD

**Issue by yanpalis** [MrCrayfish/ModelCreator#78]
![2016-04-26_19 23 24](https://cloud.githubusercontent.com/assets/15308404/14823672/0649d164-0bdc-11e6-8239-29e27f70831e.png)

**Comment by yanpalis** [comment]
UPD. Every block with custom model do it.

**Comment by KnightMiner** [comment]
Are you trying to model a solid block with a transparent model? This is not a model maker issue

**Comment by yanpalis** [comment]
There is no transparent textures in model.

**Comment by KnightMiner** [comment]
Not what I mean. A "transparent model" is one that does not cull nearby blocks, such as end portal frames, glass, or hoppers. If the block is solid, it will do that in MC

**Comment by yanpalis** [comment]
But I seen resource pack with 3D model of furnace.

**Comment by MrCrayfish** [comment]
The difference is though that furnace covers up the sides of adjacent blocks. As you can see in your image, you can see the top face of the block below.
