### ISSUE TITLE
Why are rotations limited to 22.5 and 45?

### ISSUE THREAD

**Issue by gummby8** [MrCrayfish/ModelCreator#79]
Is this a limitation of the model creator or the JSON format?
I went and manually edited a part to 10 degrees rotation and re-imported it into the model creator, it looked fine until I tried to rotate it again, then it snapped to 22.5

**Comment by KnightMiner** [comment]
Its a Minecraft limitation. No reason to support something that won't work in game

**Comment by gummby8** [comment]
So even if I did manually change the rotation to something other than 22.5 or 45 minecraft would work with it......wtf is wrong with them!?

**Comment by KnightMiner** [comment]
I think it has to do with the original system being way to flexible, as plains can be used to create any 3d model really.

If you are using an item model though, you can rotate the entire model using transforms
