### ISSUE TITLE
How to compile? Error!

### ISSUE THREAD

**Issue by AyanGithub** [MrCrayfish/ModelCreator#8]
This is not really an issue, but when I tried to compile using Eclipse, I got some errors. How do you compile correctly? Thanks!

**Comment by AyanGithub** [comment]
I don't know how to compile, for short.

**Comment by AyanGithub** [comment]
Clipboard.java there's red lines (almost) everywhere I'll take a screenshot
![githubimport](https://cloud.githubusercontent.com/assets/11683855/6873846/65bc2786-d489-11e4-9d61-73be3d258af8.PNG)

**Comment by AyanGithub** [comment]
Running Windows 10 Technical Preview (my computer was just like the Windows 8.1 I had before Windows 10 Tech. Preview) 64-bit Imported from Github Clone Link

**Comment by paultorben** [comment]
You need to add in the Library JARs - right click on "ModelCreator" in "Package Explorer", and Select "Properties". Then in the "Properties for ModelCreator" dialog window, select "Java Build Path".  Select the "Libraries Tab", and click the "Add JARs ..." button. Open up "ModelCreator" in the tree, then "libs", and add all the library JARs found in there.

**Comment by AyanGithub** [comment]
Thanks! Got it up and working! :+1: :) :D

**Comment by AyanGithub** [comment]
Do you use it with Minecraft?
