### ISSUE TITLE
End U:s/end V:s are set to 1 initially

### ISSUE THREAD

**Issue by AndersBillLinden** [MrCrayfish/ModelCreator#84]
When I create a new cube, all faces has UV:s that goes from 0 to 1.
I always raise the end values to 16 because I want textures to go all over the faces instead of only covering 1/256 of the area..

Is there a point in that the end values are 1 initially?

Do everyone raise them to 16 when they have imported a texture, just like I do?

**Comment by MrCrayfish** [comment]
They are set to 1 initially by the auto UV setting and adjust accordingly to the size of your cuboid.
