### ISSUE TITLE
Can you import the models you have made into Minecraft? Or with a mod you've made?

### ISSUE THREAD

**Issue by AyanGithub** [MrCrayfish/ModelCreator#9]
If you can, then how? Or can you use it with a mod that you have made with 1.8 support?

**Comment by AyanGithub** [comment]
What do you do with the .JSON files?

**Comment by MrCrayfish** [comment]
The new JSON format is for 1.8 and higher. This program does not generate Java code as thats not how block models work anymore. Check out this post which goes over block models. http://greyminecraftcoder.blogspot.com.au/2014/12/block-models-18.html
